### ISSUE TITLE
Missing license information

### ISSUE THREAD

**Issue by wking** [nathanwinther/go-uuid4#1]
I'd like to use this code, but the licensing is unclear.  GitHub's notes on licensing are [here](https://help.github.com/articles/open-source-licensing/), if that helps you decide what to use and where to put it ;).

**Comment by nathanwinther** [comment]
I've added a MIT License. Hope this helps.

Thanks for the heads up on licensing.

Nathan

On Tue, Oct 13, 2015, at 03:18 AM, W. Trevor King wrote:

> I'd like to use this code, but the licensing is unclear.  GitHub's
> notes on licensing are here[1], if that helps you decide what to use
> and where to put it ;).
> 
> — Reply to this email directly or view it on GitHub[2].

Links:
1. https://help.github.com/articles/open-source-licensing/
2. https://github.com/nathanwinther/go-uuid4/issues/1

**Comment by wking** [comment]
On Tue, Oct 13, 2015 at 06:22:44AM -0700, Nathan Winther wrote:

> I've added a MIT License.

Great, thanks :).
